ALTER TABLE users ADD COLUMN avatar VARCHAR(255);
ALTER TABLE users ADD COLUMN language VARCHAR(10) DEFAULT 'pt-BR';
ALTER TABLE users ADD COLUMN theme VARCHAR(20) DEFAULT 'system';
ALTER TABLE users ADD COLUMN accent_color VARCHAR(20);
